---
- name: 'Ensure libselinux-python is installed'
  ansible.builtin.yum:
    name: libselinux-python'
    state: installed
  when: ansible_distribution_major_version == '7' and ansible_os_family == "RedHat"

- name: 'Ensure libselinux-python is installed'
  ansible.builtin.dnf:
    name: 'python3-libselinux'
    state: installed
  when: ansible_distribution_major_version == '8' and ansible_os_family == "RedHat"

- name: 'Set selinux state'
  ansible.posix.selinux:
    policy: targeted
    state: "{{ selinux_state }}"
