---

- name: copy rvm installation script to remote system
  template:
      src: rvm_installer.sh.j2 
      dest: /root/rvm_installer.sh

- name: prepare to run rvm installation script
  shell: |
    curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
    curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -

- name: run rvm installation script
  shell: sh /root/rvm_installer.sh

- name: Install cloudstack plugin with gem
  shell: gem install 'foreman_cpp_cloudstack'

