---
- name: Install foreman smart proxy plugins
  package:
      name: "{{ item }}"
      state: present
  ignore_errors: "{{ ansible_check_mode }}"
  with_items: "{{ foreman_smart_proxy_plugins }}"
  when: foreman_smart_proxy_plugins is defined and item is defined
  notify: restart foreman

- name: create smart-proxy key if not found
  user:
    name: foreman-proxy
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa_foreman_proxy
    ssh_key_passphrase: ""
    force: no
  
