---
- name: install system updates for {{ ansible_distribution }} systems
  ansible.builtin.dnf:
    name: *
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= '8'
  ignore_errors: "{{ ansible_check_mode }}"

- name: install development tools
  ansible.builtin.dnf:
    name: "@development"
    state: latest
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= '8'
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install katello
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  loop: "{{ katello_pkg }}"

...
