---
- name: add foreman repo
  dnf:
    disable_gpg_check: true
    name: "{{ foreman_repo }}"
    state: present

- name: add katello repo
  dnf:
    disable_gpg_check: true
    name: "{{ katello_repo }}"
    state: present

- name: add puppetlabs repo
  dnf:
    disable_gpg_check: true
    name: "{{ puppetlabs_repo }}"
    state: present

- name: add epel repo
  dnf:
    disable_gpg_check: true
    name: "{{ epel_repo }}"
    state: present

- name: add additional repositories
  dnf:
    disable_gpg_check: true
    name: "{{ item }}"
    state: present
  with_items: "{{ katello_extra_repos }}"
  when: katello_extra_repos is defined

- name: reset ruby module stream
  shell: dnf module -y reset ruby

- name: reset postgresql module stream
  shell: dnf module -y reset postgresql

- name: configure powertools repo
  shell: dnf config-manager --set-enabled powertools

- name: configure dnf module streams
  shell: dnf module -y enable katello:el8 pulpcore:el8

