---
- block:
  - name: install chrony
    ansible.builtin.dnf:
      name: chrony
      state: latest
      update_cache: yes
    ignore_errors: "{{ ansible_check_mode }}"

  - name: configure chrony (marks)
    ansible.builtin.replace:
      path: /etc/chrony.conf
      regexp: '^(pool .* iburst)$'
      replace: '### {mark} ANSIBLE MANAGED BLOCK\n\1\n### {mark} ANSIBLE MANAGED BLOCK'
    ignore_errors: "{{ ansible_check_mode }}"

  - name: configure chrony (ntp servers)
    ansible.builtin.blockinfile:
      path: /etc/chrony.conf
      marker: "### {mark} ANSIBLE MANAGED BLOCK" 
      content: |
        {% if ntpserves is defined %}
        {% for ntpserver in ntpservers %}
        server {{ ntpserver }} iburst
        {% endfor %}

        # Ignore stratum in source selection.
        stratumweight 0
        {% else %}
        pool 2.pool.ntp.org iburst
        {% endif %}

  - name: configure chrony service
    ansible.builtin.systemd:
      name: chronyd
      state: restarted
      enabled: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version >= '8'

